### ISSUE TITLE
Why not use alpine 3.7 (´･_･`)?

### ISSUE THREAD

**Issue by mritd** [alexdoesh/mtproxy#1]
Why not use alpine 3.7 (´･_･`)?

**Comment by alexdoesh** [comment]
You're totally right, just wanted to make it flexible (but started from my favorite base image), so going to add multiple base images support (via template and script, how official Docker images usually do, like https://github.com/docker-library/python). If you want, you're welcome with PR, I probably will take care of this only in the end of the week.
